name: Build
on:
  push: { branches: [main, dev] }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Go env
        run: go env

      - name: Tidy & vendor check
        run: |
          go mod tidy
          git diff --exit-code || (echo "::error::go.mod/go.sum are not tidy"; exit 1)

      - name: Vet
        run: go vet ./...

      - name: Build server
        run: |
          mkdir -p dist
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -trimpath -ldflags "-s -w" -o dist/server ./cmd/server
          file dist/server

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: server-linux-amd64
          path: dist/server
