name: PR Code Analysis

on:
  push: { branches: [main, dev] }
  pull_request: { branches: [main, dev] }

jobs:
  code-quality:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    env:
      GOTOOLCHAIN: auto
      # mirror the secret into env so we can use it in `if:`
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Upload coverage.out
        uses: actions/upload-artifact@v4
        with:
          name: coverage-out
          path: coverage.out

      - name: SonarCloud Scan
        if: ${{ env.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.projectVersion=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
