name: PR Code Analysis

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  code-quality:
    runs-on: ubuntu-22.04
    env:
      GOTOOLCHAIN: auto

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Cache Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout 5m

      - name: Vet
        run: go vet ./...

      - name: Test (race + coverage)
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage.out
        uses: actions/upload-artifact@v4
        with:
          name: coverage-out
          path: coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
