name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      GOTOOLCHAIN: auto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build (linux/amd64)
        run: |
          mkdir -p dist
          VERSION="${GITHUB_REF_NAME}"
          COMMIT="${GITHUB_SHA::7}"
          DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -trimpath \
              -ldflags "-s -w -X main.version=${VERSION} -X main.commit=${COMMIT} -X main.date=${DATE}" \
              -o dist/go-chat-backend_linux_amd64 ./cmd/server
          (cd dist && sha256sum go-chat-backend_linux_amd64 > SHA256SUMS)

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            dist/go-chat-backend_linux_amd64
            dist/SHA256SUMS
