name: Test
on:
  push: { branches: [main, dev] }
  pull_request: { branches: [main, dev] }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Format check (go fmt)
        run: |
          fmt_out=$(gofmt -l .)
          if [ -n "$fmt_out" ]; then
            echo "::error::Files not formatted:"
            echo "$fmt_out"
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Test
        run: |
          go test ./... -count=1 -covermode=atomic -coverpkg=./... -coverprofile=coverage.out -v
          go tool cover -func=coverage.out | tee coverage.txt
          go tool cover -html=coverage.out -o coverage.html
          # lcov
          GOROOT=$(go env GOROOT) go install github.com/jandelgado/gcov2lcov@latest
          "$(go env GOPATH)"/bin/gcov2lcov -infile=coverage.out -outfile=coverage.lcov

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.out
            coverage.txt
            coverage.html
            coverage.lcov
